pub const ERR_ARG_NOT_CONVERTIBLE_TO_UTF_8: &str = "Error: supplied command-line argument not convertible to UTF-8";
pub const ERR_EMPTY_PRODUCT_PRICING_TABLE: &str = "Error: Cannot build an empty product pricing table";
pub const ERR_INTERNAL_KVP_ALREADY_PRESENT: &str = "Internal error: Unexpected key/value pair already present in product table";
pub const ERR_UNREPRESENTABLE_VALUE: &str = "Error: Calculation yield unrepresentable result (result is too small or too large?)";
pub const ERR_PRODUCT_NOT_FOUND: &str = "Error: Product was not found in the price list (product, price list)";
pub const ERR_PRICING_NOT_FOUND_AT_QUANTITY: &str = "Error: No pricing information for `product` at `quantity` in `product price list`: ";
pub const ERR_INTERNAL_ZERO_USED_WITH_NON_ZERO_TYPE: &str = "Internal error: Invalid constant value supplied--cannot use 0 with a `NonZero*` type";
pub const ERR_INVALID_PRODUCT_MNEMONIC: &str = "Error: Invalid product mnemonic supplied.  No corresponding `Product` found";
pub const ERR_INTERNAL_EXPECTED_UNCONDITIONAL_SOME: &str = "Internal Error: `None` encountered when an unconditional `Some` was expected";
